services:
  - type: cron
    name: wind-calendar-sync
    runtime: python
    schedule: "5 * * * *"
    buildCommand: ""
    startCommand: python3 calendar_sync.py
  - type: web
    name: wind-calendar
    runtime: static
    buildCommand: ""
    staticPublishPath: ./public
  - type: web
    name: wind-calendar-feed
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python3 feed_server.py
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: wind-calendar-kv
          property: connectionString
  - type: keyvalue
    name: wind-calendar-kv
    plan: free
    ipAllowList: []
